security:
  enabled: false
spring:
#  profiles:
#    include: security
  application:
    name: edo-scheduler
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true