#Докер файл для созданный для запуска 4 сервисов: minio, postgres, rabbitMQ и keycloak

#Для запуска всех сервисов нажимаем на двойную стрелку
#Для запуска отдельных сервисов нажимаем стрелку напротив нужного
version: '3'
services:
  #minio
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=access_key
      - MINIO_ROOT_PASSWORD=secret_key
    volumes:
      - minio_data:/data
    command: server /data

  #postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=edo_db

  #postgres
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  #keycloak
  keycloak:
    image: jboss/keycloak
    ports:
      - 8888:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=edo_db
      - DB_USER=postgres
      - DB_PASSWORD=root
    depends_on:
      - postgres

volumes:
  minio_data: