security:
  enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  #  profiles:
  #      include: security
  flyway:
    host: localhost
  application:
    name: edo-service
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${spring.flyway.host}:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}