spring:
  application:
    name: edo-service
  rabbitmq:
    exchange: edo.direct
    queues:
      addressCreate: address.create.service
      addressCreateDB: address.create.DB
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}