package ResolutionTest;

public final class TestJsonStrings {
    public static final String SINGLE_RESOLUTION = """
            {
                "id": null,
                "creationDate": null,
                "archivedDate": null,
                "lastActionDate": null,
                "enumResolution": "Резолюция",
                "creator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "signer": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "executors": [{
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                   "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                }],
                "curator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "question": null,
                "deadlines": []
            }""";

    public static final String RESOLUTION_WITHOUT_EXECUTORS = """
            {
                "id": null,
                "creationDate": null,
                "archivedDate": null,
                "lastActionDate": null,
                "enumResolution": "Резолюция",
                "creator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "signer": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "executors": [],
                "curator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "question": null,
                "deadlines": []
            }""";

    public static final String RESOLUTION_WITHOUT_ADDRESSERS = """
            {
                "id": null,
                "creationDate": null,
                "archivedDate": null,
                "lastActionDate": null,
                "enumResolution": "Резолюция",
                "creator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "signer": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "executors": [],
                "curator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "question": null,
                "deadlines": []
            }""";

    public static final String RESOLUTION_WITHOUT_SIGNERS = """
            {
                "id": null,
                "creationDate": null,
                "archivedDate": null,
                "lastActionDate": null,
                "enumResolution": "Резолюция",
                "creator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "signer": null,
                "executors": [{
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                   "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                }],
                "curator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "question": null,
                "deadlines": []
            }""";

    public static final String RESOLUTION_WITH_ONE_ADDRESSEE = """
            {
                "id": null,
                "creationDate": null,
                "archivedDate": null,
                "lastActionDate": null,
                "enumResolution": "Резолюция",
                "creator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "signer": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "executors": [{
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                   "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                }],
                "curator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "question": null,
                "deadlines": []
            }""";


    public static final String RESOLUTION_WITH_SEVERAL_ADDRESSEE =  """
            {
                "id": null,
                "creationDate": null,
                "archivedDate": null,
                "lastActionDate": null,
                "enumResolution": "Резолюция",
                "creator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "signer": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "executors": [{
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },{
                    "id": null,
                    "firstName": "Иван",
                    "lastName": "Иванов",
                    "middleName": "Иванович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Иванову Ивану Ивановичу",
                    "fioNominative": "Иван Иванович Иванов",
                    "fioGenitive": "Иванова Ивана Ивановича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "ivanov_i",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                      }],
                "curator": {
                    "id": null,
                    "firstName": "Дмитрий",
                    "lastName": "Рейн",
                    "middleName": "Константинович",
                    "address": "Address",
                    "photoUrl": null,
                    "fioDative": "Рейну Дмитрию Константиновичу",
                    "fioNominative": "Дмитрий Константинович Рейн",
                    "fioGenitive": "Рейна Дмитрия Константиновича",
                    "externalId": "1ef2eeb4-c861-4b48-b682-e9eb08c0f163",
                    "phone": "+79776020338",
                    "workPhone": "+79786039037",
                    "workEmail": "room083@gmail.com",
                    "birthDate": "2023-04-25T11:26:04.3683958+03:00",
                    "username": "reyn_d",
                    "creationDate": null,
                    "archivedDate": null,
                    "notification": null
                },
                "question": null,
                "deadlines": []
            }""";
}
