security:
  enabled: false
spring:
#  profiles:
#      include: security
  flyway:
    host: localhost
  application:
    name: edo-rest
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${spring.flyway.host}:8761/eureka}
  instance:
    preferIpAddress: true
