security:
  enabled: false
spring:
#  profiles:
#      include: security
  application:
    name: edo-rest
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

