security:
  enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  #  profiles:
  #      include: security
  application:
    name: edo-rest
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

