spring:
  application:
    name: edo-rest
  rabbitmq:
    exchange: edo.direct
    queues:
      addressCreate: address.create.service
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


