security:
  enabled: false
spring:
#  profiles:
#    include: security
  application:
    name: edo-integration
  rabbitmq:
    password: guest
    username: guest
  mail:
    host: localhost
    port: 3025
    username: bc3c2e87-85c2-461a-b311-5b80f84f0d75
    password: a0f3bb95-db89-47bf-b6ed-8c9ad227b107
    test-connection: true # Проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true