security:
  enabled: false
spring:
#  profiles:
#    include: security
  application:
    name: edo-integration
  rabbitmq:
    password: guest
    username: guest
  mail:
    host: app.debugmail.io
    port: 25
    username: a5ae3681-2cee-4604-b9e1-1c31e8fdba67
    password: d71639cd-4d78-4344-af83-ddeb90f46c6c
    test-connection: true # Проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true