security:
  enabled: false
spring:
  #  profiles:
  #    include: security
  application:
    name: edo-integration
  rabbitmq:
    password: guest
    username: guest
  mail:
    host: app.debugmail.io
    port: 25
    username: 693260b6-33db-4008-abf7-2f1d9b72a917
    password: 13b8155b-97a6-4824-a89c-e7a77919ddae
    test-connection: true # Проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          network:
            default credentials: false
          auth: true
          enableSsl: false
          starttls:
            enable: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}