security:
  enabled: false
spring:
#  profiles:
#    include: security
  application:
    name: edo-integration
  mail:
    host: smtp.gmail.com
    port: 587
    username: test.acc.for.edo.project@gmail.com
    password: "sxagjtxflospyrgm"
    test-connection: true # Проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true