spring:
  flyway:
    enabled: true
    user: postgres
    password: oog
    url: jdbc:postgresql://localhost:5432/edo_db
    default-schema: edo
    locations: db/migration
  application:
    name: edo-repository
  jpa:
    properties:
      hibernate:
        default_schema: edo
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
