security:
  enabled: false
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edo-project-client
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/edo-project-realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}
          jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/certs
  jpa:
    properties:
      hibernate:
        default_schema: edo
  flyway:
    enabled: true
    user: root
    password: root
    url: jdbc:postgresql://localhost:5432/edo_db?currentSchema=${spring.flyway.default-schema}
    default-schema: edo
    locations: db/migration
    out-of-order: true
  application:
    name: edo-repository
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}