spring:
  jpa:
    properties:
      hibernate:
        default_schema: edo
  flyway:
    enabled: true
    user: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/edo_db?currentSchema=${spring.flyway.default-schema}
    default-schema: edo
    locations: db/migration
    out-of-order: true
  application:
    name: edo-repository
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
