security:
  enabled: false
spring:
  application:
    name: edo-file-storage
server:
  port: 9010
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
minio:
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint: http://localhost:9000
  bucket: test